version: "3.9"

services:
  # PostgreSQL database service
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"  # Host:Container port mapping
    volumes:
      - ./data:/var/lib/postgresql/data/  # Volume for persistent data
    networks:
      - backend  # Attached to the 'promotion_backend' network

  # Redis caching service
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"  # Host:Container port mapping
    networks:
      - backend  # Attached to the 'promotion_backend' network

networks:
  backend:
    driver: bridge  # Using the bridge network driver
