version: "3.9"

services:
  # PostgreSQL database service
  db:
    container_name: db
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    ports:
      - "5432:5432"  # Host:Container port mapping
    volumes:
      - ${PGADTA_PATH:-./data}:${PGDATA:-/data/postgres}
    networks:
      - backend  # Attached to the 'promotion_backend' network
    restart: unless-stopped

  # Redis caching service
  redis:
    container_name: redis
    build: redis
    ports:
      - "6379:6379"  # Host:Container port mapping
    networks:
      - backend  # Attached to the 'promotion_backend' network

networks:
  backend:
    driver: bridge  # Using the bridge network driver
